# Generated by Django 5.1.5 on 2025-01-29 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('github', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 1, 29, 15, 4, 4, 439331, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
