# Generated by Django 5.1.5 on 2025-01-29 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetails',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 1, 29, 15, 9, 38, 381702, tzinfo=datetime.timezone.utc)),
        ),
    ]
