# Generated by Django 5.1.5 on 2025-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydetails', '0003_remove_mydetails_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetails',
            name='current_datetime',
            field=models.DateTimeField(verbose_name='2025-01-30T11:05:07.521708+00:00'),
        ),
    ]
