# Generated by Django 5.1.5 on 2025-02-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydetails', '0004_alter_mydetails_current_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyDetails',
        ),
    ]
